from typing import Dict, Any, List
from app.core.logging_config import logger

class RecommendationAgent:
    """
    Recommendation Agent
    Responsibilities:
    - compare suppliers & model outputs
    - generate unified recommendation
    - calculate recommendation confidence
    - provide detailed explanation
    """
    def __init__(self):
        self.agent_name = "Recommendation Agent"

    def synthesize_recommendation(
        self,
        procurement_data: dict,
        risk_result: dict,
        rag_result: dict,
        qwen_result: dict,
        contract_result: dict
    ) -> dict:
        logger.info(f"[{self.agent_name}] Synthesizing recommendation...")

        risk_score = risk_result.get("risk_score", 0.5)
        risk_level = risk_result.get("risk_level", "MEDIUM")
        rag_docs = rag_result.get("results", [])

        # Calculate confidence score based on model agreement and RAG similarity
        top_rag_score = rag_docs[0]["score"] if rag_docs else 0.5
        confidence = round(float(0.4 * (1.0 - risk_score) + 0.6 * top_rag_score), 4)
        confidence = min(0.98, max(0.45, confidence))

        # Check if Qwen generated output
        qwen_rec = qwen_result.get("recommendation") if qwen_result else None
        
        if qwen_rec:
            recommendation_text = qwen_rec
            reasoning = qwen_result.get("reasoning", "Generated by Qwen LoRA LLM based on RAG context and risk factors.")
        else:
            # Structurally synthesize agent recommendations without fake LLM claims
            if risk_level == "HIGH":
                recommendation_text = f"Proceed with caution. Request two-stage bidding with strict performance security guarantee for '{procurement_data.get('title')}' due to high XGBoost risk score ({risk_score})."
            elif risk_level == "MEDIUM":
                recommendation_text = f"Approve procurement for '{procurement_data.get('title')}' subject to standard technical evaluation and 5% EMD security."
            else:
                recommendation_text = f"Approve open competitive tender for '{procurement_data.get('title')}' with standard HP PWD terms."
            
            reasoning = f"Synthesized from XGBoost risk model (Score: {risk_score}, Level: {risk_level}) and FAISS retrieval of {len(rag_docs)} historical tender references."

        suggested_action = "REQUIRE_HUMAN_APPROVAL" if (risk_score >= 0.4 or budget_exceeds(procurement_data)) else "AUTO_APPROVE"

        return {
            "agent": self.agent_name,
            "recommendation": recommendation_text,
            "reasoning": reasoning,
            "confidence": confidence,
            "suggested_action": suggested_action,
            "risk_summary": {
                "risk_score": risk_score,
                "risk_level": risk_level
            },
            "top_similar_tenders_count": len(rag_docs)
        }

def budget_exceeds(pdata: dict) -> bool:
    return float(pdata.get("budget", 0)) >= 1000000

recommendation_agent = RecommendationAgent()
